var json = {
  "philistine": "materialistic in outlook; uncultured",
  "gorgoneion": "representation of the gorgon's head",
  "roodge": "to push or lift with effort",
  "philogyny": "love of women",
  "conspecies": "different species that are part of the same genus",
  "tartarology": "beliefs about hell or the underworld",
  "smaragdine": "emerald green",
  "pseudocide": "pretended attempt at suicide",
  "wamus": "cardigan or jacket buttoned at neck and wrists",
  "xerothermic": "dry and hot",
  "devisee": "one to whom property is bequeathed in a will",
  "birostrate": "double-beaked",
  "perulate": "scaly; having scaled skin",
  "panentheism": "belief that world is part but not all of God's being",
  "nucha": "the nape of the neck",
  "steven": "outcry; loud call",
  "pericope": "an excerpt or passage read during religious services",
  "nasillate": "to speak in a nasal manner",
  "lupulic": "of, like or pertaining to hops",
  "saxatile": "rock-dwelling",
  "schizotrichia": "splitting of hair",
  "rancelman": "local constable or law officer in Orkney and Shetland",
  "snath": "curved handle or shaft of a scythe",
  "campagnol": "short-tailed field mouse",
  "diegesis": "the narration of facts",
  "biometrics": "study of biological measurement",
  "gratulatory": "congratulatory",
  "washboard": "broad thin plank along ship's gunwale to keep out sea water",
  "oncogenesis": "producing cancerous tumours",
  "tabefaction": "wasting away; emaciation",
  "anaclastic": "refractive; of, like or pertaining to refraction",
  "heliac": "solar; coincident with that of the sun",
  "spumescent": "foamy; frothing",
  "viator": "traveller; wayfarer",
  "mnemotechny": "system for improving memory",
  "enation": "outgrowth; extension",
  "piolet": "ice-axe",
  "scapiform": "shaped like a stalk",
  "fleer": "to mock; to jeer; to make faces in contempt",
  "chock": "metal casting with curved arms for passing ropes for mooring ship",
  "catenular": "chain-like",
  "thalassian": "marine; type of sea turtle",
  "vermifugal": "expelling worms",
  "monoblepsia": "colour-blindness for all but one colour",
  "assot": "to befool; to besot",
  "lagan": "cargo jettisoned from ship but marked by buoys for recovery",
  "gement": "groaning, lamenting",
  "stupe": "medicated cloth used to treat fever",
  "membral": "of, like or pertaining to the limbs rather than the trunk",
  "hexaemeron": "period of six days of creation",
  "witling": "one who utters markedly feeble witticisms",
  "hommock": "ridge in an ice field",
  "arceate": "to prevent; to ward off",
  "multure": "fee for grinding grain",
  "cinnabar": "red crystalline mercuric sulfide pigment; deep red or scarlet colour",
  "belonoid": "shaped like a needle",
  "telematics": "transmission of computerized data over long distances",
  "asperity": "roughness of surface or sound",
  "prolusion": "preliminary performance, activity or display",
  "decalescence": "point in heating metal where it appears to cool",
  "quercine": "of, like or pertaining to oak trees",
  "ovuliferous": "bearing ovules",
  "iconolatry": "image-worship",
  "chessel": "cheese-mould",
  "vibratile": "capable of vibratory motion",
  "arguria": "silver poisoning",
  "zander": "a variety of European perch",
  "celadon": "pale green; pale green glazed pottery",
  "jackanapes": "impudent child; conceited fellow",
  "phalarope": "migratory shorebird with lobed feet",
  "tractile": "ductile; able to be drawn out",
  "lepid": "pleasant; charming; amusing",
  "disinure": "to render unfamiliar",
  "barcarole": "gondolier's song",
  "champerty": "illegal contract to finance a lawsuit for a percentage fee",
  "ineluctable": "against which it is useless to struggle",
  "ahull": "with sails furled and helm lashed to the lee-side",
  "harpagon": "harpoon",
  "sectiuncle": "small section",
  "yew": "to rise, as a layer of froth in a boiling liquid",
  "miscegene": "person of mixed racial heritage",
  "polacca": "stately Polish dance; polonaise",
  "octroi": "trading privilege, monopoly or concession granted to a town",
  "aeolipyle": "hollow ball that turns through steam escaping through valves",
  "natheless": "nevertheless; notwithstanding",
  "anthracomancy": "divination using burning coals",
  "precentor": "leader of the singing of a church choir",
  "welter": "to be in a state of turmoil or chaos",
  "hieromancy": "divination by studying objects offered in sacrifice",
  "stereopsis": "stereoscopic or three-dimensional vision",
  "trimacular": "having three spots or marks",
  "empanoply": "to clothe in full armor",
  "rhinotillexomania": "compulsive nose picking",
  "perissotomist": "knife-happy surgeon",
  "lambrequin": "drapery over a window or doorway; veil over a helmet",
  "apport": "to transport objects without material agency",
  "ellipsograph": "instrument for describing ellipses",
  "mittimus": "warrant granted for sending a charged person to jail",
  "revalorize": "to give new value to; to restore value of currency",
  "diptych": "pair of pictures on hinged panels; register of bishops and saints",
  "aerolith": "stone that falls from the sky; meteorite",
  "symptosis": "emaciation",
  "titian": "red-gold or reddish-brown",
  "chrisom": "white robe put on newly baptised child",
  "vagarish": "of the eyes, tending to roam",
  "fixity": "fixed state; stability; permanence",
  "gnomic": "signifying general truth; pertaining to aphorisms or proverbs",
  "flysch": "sandstone deposit",
  "virginal": "small keyed instrument like a harpsichord",
  "deaconing": "act of putting best looking goods on top of pile",
  "latescent": "becoming latent",
  "puy": "small volcanic cone",
  "cryptous": "of, like or pertaining to crypts",
  "czardas": "Hungarian dance that increases in speed",
  "brassard": "badge worn on the arm; piece of armour for the arm",
  "pace": "contrary to the opinion of; in respectful disagreement with",
  "gouache": "opaque watercolour paint",
  "ostensory": "container for holding consecrated Communion wafers",
  "xyloid": "woody; ligneous",
  "phonautograph": "instrument for recording sound vibrations",
  "grimoire": "magician's book for summoning spirits",
  "retree": "slightly damaged paper",
  "iconomancy": "divination using icons",
  "virilia": "male reproductive organs",
  "wherret": "a blow on the ear or side of the head",
  "rubedinous": "ruddy",
  "phrenic": "of or near the midriff",
  "sponsalia": "espousals",
  "lumpenintelligentsia": "those of the intellectual class regarded disparagingly as of little worth",
  "muricide": "killing or killer of mice or rats",
  "pantheism": "belief that the universe is God; belief in many gods",
  "hexamerous": "having six parts",
  "isodiabatic": "having equal transmission of heat",
  "circumcrescent": "growing around; above or over",
  "grillage": "framework of timber",
  "thropple": "throat or windpipe of an animal",
  "thanatopsis": "view of or reflection upon death",
  "nitency": "brightness; lustrousness",
  "tarrish": "of the quality or consistency of tar",
  "effutiation": "twaddle; humbug",
  "symploce": "repetition of word at start of one and end of next clause",
  "soutache": "narrow braid used for trimming",
  "baroscope": "weather-glass",
  "cambresine": "fine linen fabric",
  "crural": "of or belonging to the leg",
  "rhipidate": "fan-shaped",
  "geminiform": "paired; double",
  "coelom": "body cavity; abdomen",
  "exemplum": "short story or anecdote with a moral",
  "halieutic": "of, like or pertaining to fishing",
  "criophore": "sculpture of a man carrying a ram",
  "theodidact": "student of God; one who is taught by God",
  "luxation": "dislocation of an anatomical part",
  "myrmecophilous": "having a symbiotic relationship with ants",
  "opacimeter": "instrument for measuring opacity",
  "barn": "unit of area measurement of particles equal to 100 square femtometres",
  "aisling": "a vision or dream",
  "didascalic": "didactic; pertaining to education or teaching",
  "phaeic": "dusky",
  "melalgia": "pain in the limbs",
  "cwm": "valley or glen",
  "granivorous": "feeding on seeds",
  "epideictic": "done for show or display",
  "butyraceous": "resembling, producing or having the qualities of butter",
  "anastrophe": "reversing or inverting word order as rhetorical device",
  "maskirovka": "use of deception or camouflage as military stratagem",
  "scintillant": "sparkling",
  "hippomancy": "divination using horses",
  "clerisy": "scholars and educated people as a class",
  "parabasis": "speech where the chorus advances and addresses audience",
  "cnicnode": "point where tangents form a cone of the second order",
  "spectroscope": "instrument for forming spectra by dispersing rays of light",
  "wether": "castrated ram",
  "septimal": "of, like or pertaining to or based on the number seven",
  "decalvant": "removing hair; depilatory",
  "odeum": "a usually small theatre or concert hall",
  "oread": "mountain nymph",
  "pornotopia": "perfect setting for the antics of pornography",
  "dysphonia": "physical abnormality causing speech impediment",
  "porcine": "of, like or pertaining to pigs; swinish",
  "sennet": "musical fanfare",
  "wakerife": "wakeful; indisposed to sleep",
  "slipway": "ramp sloping into water for supporting a ship",
  "tricotee": "lively old dance",
  "spongology": "study of sponges",
  "hypostyle": "pillar",
  "sack": "dry white wine or sherry from Spain",
  "rand": "border; edge; margin",
  "putois": "brush for painting pottery",
  "surplice": "loose-fitting ankle length overgarment worn by clerics",
  "shag": "dance where participants hop energetically",
  "tapul": "central ridge of the breastplate of armour",
  "valviform": "shaped like a valve",
  "arrondi": "of a heraldic device, having rounded sides",
  "interactionism": "belief that mind and body act on each other",
  "counterphobic": "seeking out situation that is feared",
  "rosette": "knot or radiating loops of ribbon concentrically arranged",
  "suberic": "of or pertaining to cork",
  "runnel": "little brook",
  "sgraffito": "scratching surface of pottery to reveal different colour",
  "tallage": "feudal tax of a lord on tenants; any tax or toll",
  "theurgy": "magic or miracles by the agency of good spirits",
  "tachyscope": "early cinematograph",
  "sunbittern": "brightly coloured South American bird",
  "mixotrophic": "combining different modes of nutrition",
  "pentheraphobia": "fear or hatred of one's mother-in-law",
  "ambo": "early Christian raised reading desk or pulpit",
  "rafale": "burst of artillery in quick rounds",
  "muleteer": "mule-driver",
  "mattock": "pickaxe for loosening soil",
  "dispone": "to set in order; dispose",
  "textrine": "of, like or pertaining to weaving",
  "indicia": "indicating marks or symptoms",
  "legicide": "killer or destroyer of laws",
  "hither": "to this place",
  "aerophobia": "fear of flying or draughts",
  "spermology": "study of seeds",
  "piend": "a salient angle",
  "hygrology": "study of humidity",
  "sarcoid": "flesh-like",
  "irrelate": "unrelated",
  "psychodynamic": "concerning psychological motives and causation",
  "prunt": "moulded glass ornament attached to a larger glass object",
  "electrostatics": "study of static electricity",
  "charnel": "hinge of a helmet for the visor",
  "fantigue": "anxiety or irritation",
  "occipital": "of, like or pertaining to the back of the head",
  "suffrutescent": "having a woody base",
  "fingent": "moulding; shaping",
  "exodist": "one who goes out; emigrant",
  "volar": "of, like or pertaining to the palm or the sole; of, like or pertaining to flight",
  "xystarch": "ancient Greek officer in charge of gymnastic exercises",
  "pight": "to pitch",
  "prescind": "to cut off; cut short; separate",
  "quinible": "high-pitched voice; a musical part pitched very high",
  "solum": "ground; soil; piece of ground",
  "esclandre": "notoriety; unpleasantness",
  "resistentialism": "humorous theory that inanimate objects display malice towards humans",
  "yabby": "small edible freshwater crayfish",
  "duteous": "devoted to duty; obedient",
  "heterothermal": "taking the temperature of the surroundings",
  "somniferous": "bearing sleep",
  "estreat": "to consult court records in order to enable prosecution"
}

var word = document.getElementsByClassName("word");
var description = document.getElementsByClassName("description");
var dash = document.getElementsByClassName("dash");

word[0].innerHTML = "insert word";
description[0].innerHTML = "insert description";

dash[0].addEventListener('click', function () {
  document.body.innerHTML="<img src='dash.png'>"; 
});